use core::any::Any;
use std::collections::{BTreeMap, LinkedList, VecDeque};
use std::hint::black_box;

use iai_callgrind::{
  Callgrind, EventKind, LibraryBenchmarkConfig, library_benchmark, library_benchmark_group, main,
};
use typex::{
  AnyRef, MapAccess, MapEntryVisitor, Meta, MetaMut, MutationBatch, Object, ObjectRef,
  ObjectRefMut, OwnedPath, PatchOperation, PathSegment, Reflect, SequenceAccessMut,
};

#[derive(typex_derive::Meta, typex_derive::MetaMut)]
struct Profile {
  count: u16,
  label: &'static str,
}

#[derive(typex_derive::Meta, typex_derive::MetaMut)]
struct PatchState {
  profile: Profile,
  labels: BTreeMap<String, u8>,
  items: Vec<u8>,
}

fn state() -> PatchState {
  PatchState {
    profile: Profile {
      count: 1,
      label: "before",
    },
    labels: BTreeMap::from([(String::from("primary"), 1)]),
    items: vec![1, 2, 3],
  }
}

fn operations() -> [PatchOperation<'static>; 7] {
  [
    PatchOperation::set(
      [PathSegment::Field("profile"), PathSegment::Field("count")],
      7_u16,
    ),
    PatchOperation::insert_key([PathSegment::Field("labels")], "secondary", 2_u8),
    PatchOperation::remove_key([PathSegment::Field("labels")], "primary"),
    PatchOperation::insert_item([PathSegment::Field("items")], 1, 8_u8),
    PatchOperation::push_item([PathSegment::Field("items")], 9_u8),
    PatchOperation::remove_item([PathSegment::Field("items")], 0),
    PatchOperation::move_item([PathSegment::Field("items")], 0, 3),
  ]
}

fn apply_input() -> (PatchState, [PatchOperation<'static>; 7]) {
  (state(), operations())
}

#[library_benchmark]
#[bench::default(setup = apply_input)]
fn apply_patch((mut value, operations): (PatchState, [PatchOperation<'static>; 7])) -> PatchState {
  ObjectRefMut::new(&mut value).apply(operations).unwrap();
  black_box(value)
}

#[library_benchmark]
#[bench::default(setup = apply_input)]
fn mutation_batch_commit(
  (mut value, operations): (PatchState, [PatchOperation<'static>; 7]),
) -> PatchState {
  let batch = MutationBatch::from(operations);
  let _rollback = batch.commit(&mut value).unwrap();
  black_box(value)
}

#[library_benchmark]
#[bench::default(setup = state)]
fn nested_field_path(value: PatchState) -> u16 {
  let result = ObjectRef::new(&value)
    .field_path(&[PathSegment::Field("profile"), PathSegment::Field("count")]);
  black_box(result).unwrap().to_ref::<u16>().copied().unwrap()
}

fn path_segments() -> [PathSegment<'static>; 6] {
  [
    PathSegment::Field("profile"),
    PathSegment::Field("addresses"),
    PathSegment::Item(12),
    PathSegment::Key("secondary"),
    PathSegment::Item(1234),
    PathSegment::Field("count"),
  ]
}

#[library_benchmark]
#[bench::default(setup = path_segments)]
fn owned_path_from_slice(segments: [PathSegment<'static>; 6]) -> OwnedPath {
  black_box(OwnedPath::from(segments.as_slice()))
}

fn owned_path_input() -> OwnedPath {
  OwnedPath::from(path_segments().as_slice())
}

#[library_benchmark]
#[bench::default(setup = owned_path_input)]
fn owned_path_iter(path: OwnedPath) -> OwnedPath {
  for segment in &path {
    black_box(segment);
  }
  path
}

fn whole_value_input() -> (Profile, Object) {
  let replacement = Profile {
    count: 7,
    label: "after",
  };
  (state().profile, Object::new(replacement))
}

// Compare with `set_via_replace` to measure the allocation that the in-place
// `set_dyn` generated by the derive avoids.
#[library_benchmark]
#[bench::default(setup = whole_value_input)]
fn set_in_place((mut value, replacement): (Profile, Object)) -> Profile {
  MetaMut::set_dyn(&mut value, replacement).unwrap();
  black_box(value)
}

// Replaces the value, then boxes and drops the previous one as a baseline for
// `set_in_place`.
#[library_benchmark]
#[bench::default(setup = whole_value_input)]
fn set_via_replace((mut value, replacement): (Profile, Object)) -> Profile {
  drop(black_box(
    MetaMut::replace_dyn(&mut value, replacement).unwrap(),
  ));
  black_box(value)
}

const MOVE_ITEM_COUNT: usize = 1024;

fn move_vec_input() -> Vec<u64> {
  (0..MOVE_ITEM_COUNT as u64).collect()
}

fn move_vec_deque_input() -> VecDeque<u64> {
  (0..MOVE_ITEM_COUNT as u64).collect()
}

fn move_linked_list_input() -> LinkedList<u64> {
  (0..MOVE_ITEM_COUNT as u64).collect()
}

#[library_benchmark]
#[bench::native(setup = move_vec_input)]
fn move_vec_native(mut value: Vec<u64>) -> Vec<u64> {
  SequenceAccessMut::move_item(&mut value, 0, MOVE_ITEM_COUNT).unwrap();
  black_box(value)
}

#[library_benchmark]
#[bench::native(setup = move_vec_deque_input)]
fn move_vec_deque_native(mut value: VecDeque<u64>) -> VecDeque<u64> {
  SequenceAccessMut::move_item(&mut value, 0, MOVE_ITEM_COUNT).unwrap();
  black_box(value)
}

#[library_benchmark]
#[bench::native(setup = move_linked_list_input)]
fn move_linked_list_native(mut value: LinkedList<u64>) -> LinkedList<u64> {
  SequenceAccessMut::move_item(&mut value, 0, MOVE_ITEM_COUNT).unwrap();
  black_box(value)
}

#[derive(Clone)]
struct EntryMap {
  entries: Vec<(String, u8)>,
}

impl Meta for EntryMap {
  fn reflect(&self) -> Reflect<'_> {
    Reflect::Map(self)
  }

  fn into_any(self: Box<Self>) -> Box<dyn Any> {
    self
  }

  fn as_any(&self) -> &dyn Any {
    self
  }
}

impl MapAccess for EntryMap {
  fn len(&self) -> usize {
    self.entries.len()
  }

  fn key(&self, key: &str) -> Option<ObjectRef<'_>> {
    self
      .entries
      .iter()
      .find(|(entry_key, _)| entry_key == key)
      .map(|(_, value)| ObjectRef::new(value))
  }

  fn keys(&self) -> Option<Vec<String>> {
    Some(self.entries.iter().map(|(key, _)| key.clone()).collect())
  }

  fn visit_entries(&self, visitor: &mut MapEntryVisitor<'_>) {
    for (key, value) in &self.entries {
      if !visitor(AnyRef::new(key), ObjectRef::new(value)) {
        break;
      }
    }
  }
}

fn equality_input() -> (EntryMap, EntryMap) {
  let left = EntryMap {
    entries: vec![
      (String::from("primary"), 1_u8),
      (String::from("secondary"), 2_u8),
    ],
  };
  (left.clone(), left)
}

fn derived_equality_input() -> (PatchState, PatchState) {
  (state(), state())
}

#[library_benchmark]
#[bench::default(setup = derived_equality_input)]
fn derived_struct_equality((left, right): (PatchState, PatchState)) -> bool {
  black_box(ObjectRef::new(&left).eq_dyn(ObjectRef::new(&right)))
}

#[library_benchmark]
#[bench::default(setup = equality_input)]
fn generic_map_equality((left, right): (EntryMap, EntryMap)) -> bool {
  black_box(ObjectRef::new(&left).eq_dyn(ObjectRef::new(&right)))
}

library_benchmark_group!(
  name = typex_group;
  // Add a versioned benchmark when its workload needs an incompatible API.
  // IAI records a new benchmark without a baseline until the next pull request.
  benchmarks = apply_patch, mutation_batch_commit, nested_field_path, owned_path_from_slice,
    owned_path_iter, generic_map_equality, derived_struct_equality, set_in_place, set_via_replace, move_vec_native, move_vec_deque_native,
    move_linked_list_native
);

main!(
  config = LibraryBenchmarkConfig::default()
    .tool(Callgrind::default().soft_limits([(EventKind::Ir, 5.0)]));
  library_benchmark_groups = typex_group
);
