use core::any::Any;
use std::collections::{BTreeMap, LinkedList, VecDeque};
use std::hint::black_box;

use iai_callgrind::{
  Callgrind, EventKind, LibraryBenchmarkConfig, library_benchmark, library_benchmark_group, main,
};
use typex::{
  AnyRef, KeyedSequenceAccess, KeyedSequenceAccessMut, MapAccess, MapEntryVisitor, Meta, MetaMut,
  MoveItemError, MutationBatch, Object, ObjectMut, ObjectOps, ObjectRef, ObjectRefMut, OwnedPath,
  PatchOperation, PathSegment, Reflect, ReflectMut, SendObject, SequenceAccess, SequenceAccessMut,
  ValueKind,
};

#[derive(typex_derive::Meta, typex_derive::MetaMut)]
struct Profile {
  count: u16,
  label: &'static str,
}

#[derive(typex_derive::Meta, typex_derive::MetaMut)]
struct PatchState {
  profile: Profile,
  labels: BTreeMap<String, u8>,
  items: Vec<u8>,
}

fn state() -> PatchState {
  PatchState {
    profile: Profile {
      count: 1,
      label: "before",
    },
    labels: BTreeMap::from([(String::from("primary"), 1)]),
    items: vec![1, 2, 3],
  }
}

fn operations() -> [PatchOperation<'static>; 7] {
  [
    PatchOperation::set(
      [PathSegment::Field("profile"), PathSegment::Field("count")],
      7_u16,
    ),
    PatchOperation::insert_key([PathSegment::Field("labels")], "secondary", 2_u8),
    PatchOperation::remove_key([PathSegment::Field("labels")], "primary"),
    PatchOperation::insert_item([PathSegment::Field("items")], 1, 8_u8),
    PatchOperation::push_item([PathSegment::Field("items")], 9_u8),
    PatchOperation::remove_item([PathSegment::Field("items")], 0),
    PatchOperation::move_item([PathSegment::Field("items")], 0, 3),
  ]
}

fn apply_input() -> (PatchState, [PatchOperation<'static>; 7]) {
  (state(), operations())
}

#[library_benchmark]
#[bench::default(setup = apply_input)]
fn apply_patch((mut value, operations): (PatchState, [PatchOperation<'static>; 7])) -> PatchState {
  ObjectRefMut::new(&mut value).apply(operations).unwrap();
  black_box(value)
}

#[library_benchmark]
#[bench::default(setup = apply_input)]
fn mutation_batch_commit(
  (mut value, operations): (PatchState, [PatchOperation<'static>; 7]),
) -> PatchState {
  let batch = MutationBatch::from(operations);
  let _rollback = batch.commit(&mut value).unwrap();
  black_box(value)
}

#[library_benchmark]
#[bench::default(setup = state)]
fn nested_field_path(value: PatchState) -> u16 {
  let result = ObjectRef::new(&value)
    .field_path(&[PathSegment::Field("profile"), PathSegment::Field("count")]);
  black_box(result).unwrap().to_ref::<u16>().copied().unwrap()
}

#[library_benchmark]
#[bench::default(setup = state)]
fn nested_item_path(value: PatchState) -> u8 {
  let result =
    ObjectRef::new(&value).field_path(&[PathSegment::Field("items"), PathSegment::Item(1)]);
  black_box(result).unwrap().to_ref::<u8>().copied().unwrap()
}

#[library_benchmark]
#[bench::default(setup = state)]
fn nested_key_path(value: PatchState) -> u8 {
  let result =
    ObjectRef::new(&value).field_path(&[PathSegment::Field("labels"), PathSegment::Key("primary")]);
  black_box(result).unwrap().to_ref::<u8>().copied().unwrap()
}

fn path_segments() -> [PathSegment<'static>; 6] {
  [
    PathSegment::Field("profile"),
    PathSegment::Field("addresses"),
    PathSegment::Item(12),
    PathSegment::Key("secondary"),
    PathSegment::Item(1234),
    PathSegment::Field("count"),
  ]
}

#[library_benchmark]
#[bench::default(setup = path_segments)]
fn owned_path_from_slice(segments: [PathSegment<'static>; 6]) -> OwnedPath {
  black_box(OwnedPath::from(segments.as_slice()))
}

fn owned_path_input() -> OwnedPath {
  OwnedPath::from(path_segments().as_slice())
}

#[library_benchmark]
#[bench::default(setup = owned_path_input)]
fn owned_path_iter(path: OwnedPath) -> OwnedPath {
  for segment in &path {
    black_box(segment);
  }
  path
}

fn whole_value_input() -> (Profile, Object) {
  let replacement = Profile {
    count: 7,
    label: "after",
  };
  (state().profile, Object::new(replacement))
}

// Compare with `set_via_replace` to measure the allocation that the in-place
// `set_dyn` generated by the derive avoids.
#[library_benchmark]
#[bench::default(setup = whole_value_input)]
fn set_in_place((mut value, replacement): (Profile, Object)) -> Profile {
  MetaMut::set_dyn(&mut value, replacement).unwrap();
  black_box(value)
}

// Replaces the value, then boxes and drops the previous one as a baseline for
// `set_in_place`.
#[library_benchmark]
#[bench::default(setup = whole_value_input)]
fn set_via_replace((mut value, replacement): (Profile, Object)) -> Profile {
  drop(black_box(
    MetaMut::replace_dyn(&mut value, replacement).unwrap(),
  ));
  black_box(value)
}

const MOVE_ITEM_COUNT: usize = 1024;

fn move_vec_input() -> Vec<u64> {
  (0..MOVE_ITEM_COUNT as u64).collect()
}

fn move_vec_deque_input() -> VecDeque<u64> {
  (0..MOVE_ITEM_COUNT as u64).collect()
}

fn move_linked_list_input() -> LinkedList<u64> {
  (0..MOVE_ITEM_COUNT as u64).collect()
}

#[library_benchmark]
#[bench::native(setup = move_vec_input)]
fn move_vec_native(mut value: Vec<u64>) -> Vec<u64> {
  SequenceAccessMut::move_item(&mut value, 0, MOVE_ITEM_COUNT).unwrap();
  black_box(value)
}

#[library_benchmark]
#[bench::native(setup = move_vec_deque_input)]
fn move_vec_deque_native(mut value: VecDeque<u64>) -> VecDeque<u64> {
  SequenceAccessMut::move_item(&mut value, 0, MOVE_ITEM_COUNT).unwrap();
  black_box(value)
}

#[library_benchmark]
#[bench::native(setup = move_linked_list_input)]
fn move_linked_list_native(mut value: LinkedList<u64>) -> LinkedList<u64> {
  SequenceAccessMut::move_item(&mut value, 0, MOVE_ITEM_COUNT).unwrap();
  black_box(value)
}

#[derive(Clone)]
struct EntryMap {
  entries: Vec<(String, u8)>,
}

impl Meta for EntryMap {
  fn reflect(&self) -> Reflect<'_> {
    Reflect::Map(self)
  }

  fn into_any(self: Box<Self>) -> Box<dyn Any> {
    self
  }

  fn as_any(&self) -> &dyn Any {
    self
  }
}

impl MapAccess for EntryMap {
  fn len(&self) -> usize {
    self.entries.len()
  }

  fn key(&self, key: &str) -> Option<ObjectRef<'_>> {
    self
      .entries
      .iter()
      .find(|(entry_key, _)| entry_key == key)
      .map(|(_, value)| ObjectRef::new(value))
  }

  fn keys(&self) -> Option<Vec<String>> {
    Some(self.entries.iter().map(|(key, _)| key.clone()).collect())
  }

  fn visit_entries(&self, visitor: &mut MapEntryVisitor<'_>) {
    for (key, value) in &self.entries {
      if !visitor(AnyRef::new(key), ObjectRef::new(value)) {
        break;
      }
    }
  }
}

/// Sequence of records that can also be found by their key.
struct KeyedSequence {
  items: Vec<(String, u8)>,
}

impl Meta for KeyedSequence {
  fn reflect(&self) -> Reflect<'_> {
    Reflect::KeyedSequence(self)
  }

  fn into_any(self: Box<Self>) -> Box<dyn Any> {
    self
  }

  fn as_any(&self) -> &dyn Any {
    self
  }
}

impl SequenceAccess for KeyedSequence {
  fn len(&self) -> usize {
    self.items.len()
  }

  fn item(&self, index: usize) -> Option<ObjectRef<'_>> {
    self.items.get(index).map(|record| ObjectRef::new(record))
  }
}

impl KeyedSequenceAccess for KeyedSequence {
  fn key(&self, key: &str) -> Option<ObjectRef<'_>> {
    self
      .items
      .iter()
      .find(|(item_key, _)| item_key == key)
      .map(|record| ObjectRef::new(record))
  }

  fn keys(&self) -> Vec<String> {
    self.items.iter().map(|(key, _)| key.clone()).collect()
  }
}

impl MetaMut for KeyedSequence {
  fn reflect_mut(&mut self) -> ReflectMut<'_> {
    ReflectMut::KeyedSequence(self)
  }

  fn set_dyn(&mut self, value: Object) -> Result<(), Object> {
    *self = value.to::<Self>()?;
    Ok(())
  }

  fn replace_dyn(&mut self, value: Object) -> Result<Object, Object> {
    let value = value.to::<Self>()?;
    Ok(Object::new(std::mem::replace(self, value)))
  }

  fn as_meta(&self) -> &dyn Meta {
    self
  }

  fn as_any_mut(&mut self) -> &mut dyn Any {
    self
  }
}

impl SequenceAccessMut for KeyedSequence {
  fn item_mut(&mut self, index: usize) -> Option<ObjectRefMut<'_>> {
    self
      .items
      .get_mut(index)
      .map(|record| ObjectRefMut::new(record))
  }

  fn remove_item(&mut self, index: usize) -> Option<Object> {
    (index < self.items.len()).then(|| Object::new(self.items.remove(index)))
  }

  fn move_item(&mut self, from: usize, to: usize) -> Result<(), MoveItemError> {
    SequenceAccessMut::move_item(&mut self.items, from, to)
  }
}

impl KeyedSequenceAccessMut for KeyedSequence {
  fn key_mut(&mut self, key: &str) -> Option<ObjectRefMut<'_>> {
    self
      .items
      .iter_mut()
      .find(|(item_key, _)| item_key == key)
      .map(|record| ObjectRefMut::new(record))
  }
}

fn keyed_sequence_input() -> KeyedSequence {
  KeyedSequence {
    items: vec![(String::from("primary"), 1), (String::from("secondary"), 2)],
  }
}

#[library_benchmark]
#[bench::default(setup = keyed_sequence_input)]
fn keyed_sequence_key(value: KeyedSequence) -> u8 {
  let result = ObjectRef::new(&value).key("secondary");
  black_box(result)
    .unwrap()
    .to_ref::<(String, u8)>()
    .unwrap()
    .1
}

// Measures access classification and a key lookup for a plain sequence.
#[library_benchmark]
#[bench::default(setup = state)]
fn plain_sequence_key_miss(value: PatchState) -> bool {
  let object = ObjectRef::new(&value.items);
  black_box(object.access_kind());
  black_box(object.key("primary").is_none())
}

fn equality_input() -> (EntryMap, EntryMap) {
  let left = EntryMap {
    entries: vec![
      (String::from("primary"), 1_u8),
      (String::from("secondary"), 2_u8),
    ],
  };
  (left.clone(), left)
}

fn derived_equality_input() -> (PatchState, PatchState) {
  (state(), state())
}

#[library_benchmark]
#[bench::default(setup = derived_equality_input)]
fn derived_struct_equality((left, right): (PatchState, PatchState)) -> bool {
  black_box(ObjectRef::new(&left) == ObjectRef::new(&right))
}

#[library_benchmark]
#[bench::default(setup = equality_input)]
fn generic_map_equality((left, right): (EntryMap, EntryMap)) -> bool {
  black_box(ObjectRef::new(&left) == ObjectRef::new(&right))
}

fn sequence_input() -> (Vec<u8>, Object) {
  (vec![1, 2, 3], Object::new(4_u8))
}

fn map_input() -> (BTreeMap<String, u8>, Object) {
  (
    BTreeMap::from([(String::from("primary"), 1)]),
    Object::new(2_u8),
  )
}

fn optional_map_input() -> (Option<BTreeMap<String, u8>>, Object) {
  let (map, value) = map_input();
  (Some(map), value)
}

#[library_benchmark]
#[bench::default(setup = sequence_input)]
fn direct_push_item((mut value, item): (Vec<u8>, Object)) -> Vec<u8> {
  let _ = black_box(ObjectRefMut::new(&mut value).push_item(item).is_ok());
  black_box(value)
}

#[library_benchmark]
#[bench::default(setup = sequence_input)]
fn direct_insert_item((mut value, item): (Vec<u8>, Object)) -> Vec<u8> {
  let _ = black_box(ObjectRefMut::new(&mut value).insert_item(1, item).is_ok());
  black_box(value)
}

#[library_benchmark]
#[bench::default(setup = sequence_input)]
fn direct_remove_item((mut value, _): (Vec<u8>, Object)) -> Vec<u8> {
  let _ = black_box(ObjectRefMut::new(&mut value).remove_item(1));
  black_box(value)
}

#[library_benchmark]
#[bench::default(setup = sequence_input)]
fn direct_move_item((mut value, _): (Vec<u8>, Object)) -> Vec<u8> {
  let _ = black_box(ObjectRefMut::new(&mut value).move_item(0, 2));
  black_box(value)
}

#[library_benchmark]
#[bench::default(setup = map_input)]
fn direct_insert_key((mut value, item): (BTreeMap<String, u8>, Object)) -> BTreeMap<String, u8> {
  let _ = black_box(
    ObjectRefMut::new(&mut value)
      .insert_key("secondary", item)
      .is_ok(),
  );
  black_box(value)
}

#[library_benchmark]
#[bench::default(setup = map_input)]
fn direct_remove_key((mut value, _): (BTreeMap<String, u8>, Object)) -> BTreeMap<String, u8> {
  let _ = black_box(ObjectRefMut::new(&mut value).remove_key("primary"));
  black_box(value)
}

#[library_benchmark]
#[bench::default(setup = optional_map_input)]
fn direct_option_insert_key(
  (mut value, item): (Option<BTreeMap<String, u8>>, Object),
) -> Option<BTreeMap<String, u8>> {
  let _ = black_box(
    ObjectRefMut::new(&mut value)
      .insert_key("secondary", item)
      .is_ok(),
  );
  black_box(value)
}

fn mutable_object_input() -> ObjectMut {
  ObjectMut::new(state().profile)
}

#[library_benchmark]
#[bench::default(setup = mutable_object_input)]
fn object_mut_into_object(value: ObjectMut) -> Object {
  black_box(value.into_object())
}

fn send_object_input() -> SendObject {
  SendObject::new(state().profile)
}

#[library_benchmark]
#[bench::default(setup = send_object_input)]
fn send_object_into_object(value: SendObject) -> Object {
  black_box(value.into_object())
}

#[library_benchmark]
#[bench::default(setup = send_object_input)]
fn send_object_failed_downcast(value: SendObject) -> Object {
  black_box(value.to::<u8>().unwrap_err())
}

#[library_benchmark]
#[bench::default(setup = mutable_object_input)]
fn object_mut_borrow(value: ObjectMut) -> ObjectMut {
  black_box(value.as_object_ref());
  value
}

#[library_benchmark]
#[bench::default(setup = mutable_object_input)]
fn object_ref_mut_borrow(mut value: ObjectMut) -> ObjectMut {
  black_box(value.as_object_ref_mut().as_object_ref());
  value
}

#[library_benchmark]
#[bench::default(setup = send_object_input)]
fn send_object_borrow(value: SendObject) -> SendObject {
  black_box(value.as_object_ref());
  value
}

fn mutable_equality_input() -> (ObjectMut, ObjectMut) {
  (mutable_object_input(), mutable_object_input())
}

#[library_benchmark]
#[bench::default(setup = mutable_equality_input)]
fn object_ref_mut_equality((mut left, mut right): (ObjectMut, ObjectMut)) -> bool {
  black_box(left.as_object_ref_mut() == right.as_object_ref_mut())
}

#[library_benchmark]
#[bench::default(setup = mutable_object_input)]
fn object_mut_debug(value: ObjectMut) -> String {
  black_box(format!("{value:?}"))
}

#[library_benchmark]
#[bench::default(setup = mutable_object_input)]
fn object_ref_mut_debug(mut value: ObjectMut) -> String {
  black_box(format!("{:?}", value.as_object_ref_mut()))
}

#[library_benchmark]
#[bench::default(setup = send_object_input)]
fn send_object_debug(value: SendObject) -> String {
  black_box(format!("{value:?}"))
}

fn keyed_patch_input() -> (KeyedSequence, [PatchOperation<'static>; 2]) {
  (
    keyed_sequence_input(),
    [
      PatchOperation::move_item([], 0, 2),
      PatchOperation::remove_item([], 0),
    ],
  )
}

#[library_benchmark]
#[bench::default(setup = keyed_patch_input)]
fn apply_keyed_patch(
  (mut value, operations): (KeyedSequence, [PatchOperation<'static>; 2]),
) -> KeyedSequence {
  ObjectRefMut::new(&mut value).apply(operations).unwrap();
  black_box(value)
}

#[library_benchmark]
#[bench::default(setup = keyed_patch_input)]
fn keyed_mutation_batch_commit(
  (mut value, operations): (KeyedSequence, [PatchOperation<'static>; 2]),
) -> KeyedSequence {
  let _rollback = MutationBatch::from(operations).commit(&mut value).unwrap();
  black_box(value)
}

fn sequence_equality_input() -> (Vec<u8>, Vec<u8>) {
  (vec![1, 2, 3], vec![1, 2, 3])
}

#[library_benchmark]
#[bench::default(setup = sequence_equality_input)]
fn sequence_equality((left, right): (Vec<u8>, Vec<u8>)) -> bool {
  black_box(ObjectRef::new(&left) == ObjectRef::new(&right))
}

fn keyed_equality_input() -> (KeyedSequence, KeyedSequence) {
  (keyed_sequence_input(), keyed_sequence_input())
}

#[library_benchmark]
#[bench::default(setup = keyed_equality_input)]
fn keyed_sequence_equality((left, right): (KeyedSequence, KeyedSequence)) -> bool {
  black_box(ObjectRef::new(&left) == ObjectRef::new(&right))
}

type Tuple = (u16, (u8, u32), &'static str);

fn tuple_input() -> Tuple {
  (1, (2, 3), "four")
}

fn tuple_equality_input() -> (Tuple, Tuple) {
  (tuple_input(), tuple_input())
}

#[library_benchmark]
#[bench::default(setup = tuple_equality_input)]
fn tuple_equality((left, right): (Tuple, Tuple)) -> bool {
  black_box(ObjectRef::new(&left) == ObjectRef::new(&right))
}

#[library_benchmark]
#[bench::default(setup = tuple_input)]
fn tuple_item_path(value: Tuple) -> u32 {
  let value = black_box(value);
  let path = [PathSegment::Item(1), PathSegment::Item(1)];
  *ObjectRef::new(&value)
    .field_path(&path)
    .unwrap()
    .to_ref::<u32>()
    .unwrap()
}

#[library_benchmark]
#[bench::default(setup = tuple_input)]
fn tuple_item_path_mut(mut value: Tuple) -> Tuple {
  let path = [PathSegment::Item(1), PathSegment::Item(0)];
  *ObjectRefMut::new(&mut value)
    .field_path_mut(&path)
    .unwrap()
    .to_mut::<u8>()
    .unwrap() = 7;
  black_box(value)
}

fn result_equality_input() -> (Result<u16, u8>, Result<u16, u8>) {
  (Ok(7), Ok(7))
}

#[library_benchmark]
#[bench::default(setup = result_equality_input)]
fn result_equality((left, right): (Result<u16, u8>, Result<u16, u8>)) -> bool {
  black_box(ObjectRef::new(&left) == ObjectRef::new(&right))
}

#[derive(typex_derive::Meta, typex_derive::MetaMut)]
enum Status {
  Ready { count: u16 },
  Pair(u8, u32),
}

#[derive(typex_derive::Meta, typex_derive::MetaMut)]
struct Wrapper(u16, u8);

fn ready_input() -> Status {
  Status::Ready { count: 3 }
}

fn pair_input() -> Status {
  Status::Pair(1, 2)
}

#[library_benchmark]
#[bench::default(setup = ready_input)]
fn enum_field_path(value: Status) -> u16 {
  let value = black_box(value);
  let path = [PathSegment::Variant("Ready"), PathSegment::Field("count")];
  *ObjectRef::new(&value)
    .field_path(&path)
    .unwrap()
    .to_ref::<u16>()
    .unwrap()
}

#[library_benchmark]
#[bench::default(setup = pair_input)]
fn enum_item_path(value: Status) -> u32 {
  let value = black_box(value);
  let path = [PathSegment::Variant("Pair"), PathSegment::Item(1)];
  *ObjectRef::new(&value)
    .field_path(&path)
    .unwrap()
    .to_ref::<u32>()
    .unwrap()
}

#[library_benchmark]
#[bench::default(setup = ready_input)]
fn enum_field_path_mut(mut value: Status) -> Status {
  let path = [PathSegment::Variant("Ready"), PathSegment::Field("count")];
  *ObjectRefMut::new(&mut value)
    .field_path_mut(&path)
    .unwrap()
    .to_mut::<u16>()
    .unwrap() = 7;
  black_box(value)
}

fn wrapper_input() -> Wrapper {
  Wrapper(1, 2)
}

#[library_benchmark]
#[bench::default(setup = wrapper_input)]
fn tuple_struct_item_path(value: Wrapper) -> u8 {
  let value = black_box(value);
  *ObjectRef::new(&value)
    .field_path(&[PathSegment::Item(1)])
    .unwrap()
    .to_ref::<u8>()
    .unwrap()
}

#[library_benchmark]
#[bench::default(setup = state)]
fn sequence_len(value: PatchState) -> Option<usize> {
  let object = black_box(ObjectRef::new(&value.items));
  black_box(object.len())
}

#[library_benchmark]
#[bench::default(setup = state)]
fn map_len(value: PatchState) -> Option<usize> {
  let object = black_box(ObjectRef::new(&value.labels));
  black_box(object.len())
}

#[library_benchmark]
#[bench::default(setup = state)]
fn struct_field_names(value: PatchState) -> usize {
  let object = black_box(ObjectRef::new(&value));
  black_box(object.field_names()).len()
}

#[library_benchmark]
#[bench::default(setup = state)]
fn map_entry_visit(value: PatchState) -> usize {
  let object = black_box(ObjectRef::new(&value.labels));
  let mut count = 0;
  object.visit_map_entries(&mut |_, _| {
    count += 1;
    true
  });
  black_box(count)
}

#[library_benchmark]
#[bench::default(setup = state)]
fn sequence_kind(value: PatchState) -> ValueKind {
  let object = black_box(ObjectRef::new(&value.items));
  black_box(object.kind())
}

library_benchmark_group!(
  name = typex_group;
  // Add a versioned benchmark when its workload needs an incompatible API.
  // IAI records a new benchmark without a baseline until the next pull request.
  benchmarks = apply_patch, mutation_batch_commit, nested_field_path, nested_item_path,
    nested_key_path, keyed_sequence_key, plain_sequence_key_miss, owned_path_from_slice,
    owned_path_iter, generic_map_equality, derived_struct_equality, set_in_place, set_via_replace, move_vec_native, move_vec_deque_native,
    move_linked_list_native, direct_push_item, direct_insert_item, direct_remove_item,
    direct_move_item, direct_insert_key, direct_remove_key, direct_option_insert_key,
    object_mut_into_object, send_object_into_object, send_object_failed_downcast,
    object_mut_borrow, object_ref_mut_borrow,
    send_object_borrow, object_ref_mut_equality, object_mut_debug, object_ref_mut_debug,
    send_object_debug, apply_keyed_patch, keyed_mutation_batch_commit, sequence_equality,
    keyed_sequence_equality, tuple_equality, tuple_item_path, tuple_item_path_mut,
    result_equality, enum_field_path, enum_item_path, enum_field_path_mut, tuple_struct_item_path,
    sequence_len, map_len, struct_field_names, map_entry_visit, sequence_kind
);

main!(
  config = LibraryBenchmarkConfig::default()
    .tool(Callgrind::default().soft_limits([(EventKind::Ir, 5.0)]));
  library_benchmark_groups = typex_group
);
